// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#include "game.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_game_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MageInfo_game_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_game_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WarriorInfo_game_2eproto;
namespace game {
class WarriorInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<WarriorInfo> _instance;
} _WarriorInfo_default_instance_;
class MageInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MageInfo> _instance;
} _MageInfo_default_instance_;
class HeroDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Hero> _instance;
  const ::game::WarriorInfo* warrior_info_;
  const ::game::MageInfo* mage_info_;
} _Hero_default_instance_;
}  // namespace game
static void InitDefaultsscc_info_Hero_game_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_Hero_default_instance_;
    new (ptr) ::game::Hero();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::game::Hero::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_Hero_game_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_Hero_game_2eproto}, {
      &scc_info_WarriorInfo_game_2eproto.base,
      &scc_info_MageInfo_game_2eproto.base,}};

static void InitDefaultsscc_info_MageInfo_game_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_MageInfo_default_instance_;
    new (ptr) ::game::MageInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::game::MageInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MageInfo_game_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MageInfo_game_2eproto}, {}};

static void InitDefaultsscc_info_WarriorInfo_game_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_WarriorInfo_default_instance_;
    new (ptr) ::game::WarriorInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::game::WarriorInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_WarriorInfo_game_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_WarriorInfo_game_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_game_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_game_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_game_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_game_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::WarriorInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::game::WarriorInfo, weapon_),
  PROTOBUF_FIELD_OFFSET(::game::WarriorInfo, arrows_number_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::MageInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::game::MageInfo, spellbook_),
  PROTOBUF_FIELD_OFFSET(::game::MageInfo, mana_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::Hero, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::game::Hero, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::game::Hero, name_),
  PROTOBUF_FIELD_OFFSET(::game::Hero, hp_),
  PROTOBUF_FIELD_OFFSET(::game::Hero, xp_),
  offsetof(::game::HeroDefaultTypeInternal, warrior_info_),
  offsetof(::game::HeroDefaultTypeInternal, mage_info_),
  PROTOBUF_FIELD_OFFSET(::game::Hero, class_specific_info_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::game::WarriorInfo)},
  { 7, -1, sizeof(::game::MageInfo)},
  { 14, -1, sizeof(::game::Hero)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::game::_WarriorInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::game::_MageInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::game::_Hero_default_instance_),
};

const char descriptor_table_protodef_game_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\ngame.proto\022\004game\"B\n\013WarriorInfo\022\034\n\006wea"
  "pon\030\001 \001(\0162\014.game.Weapon\022\025\n\rarrows_number"
  "\030\002 \001(\003\"8\n\010MageInfo\022\036\n\tspellbook\030\001 \003(\0162\013."
  "game.Spell\022\014\n\004mana\030\002 \001(\003\"\223\001\n\004Hero\022\014\n\004nam"
  "e\030\001 \001(\t\022\n\n\002hp\030\002 \001(\003\022\n\n\002xp\030\003 \001(\003\022)\n\014warri"
  "or_info\030\004 \001(\0132\021.game.WarriorInfoH\000\022#\n\tma"
  "ge_info\030\005 \001(\0132\016.game.MageInfoH\000B\025\n\023class"
  "_specific_info*,\n\005Spell\022\r\n\tFROSTBOLT\020\000\022\024"
  "\n\020FIRESELFDESTRUCT\020\001*\034\n\006Weapon\022\t\n\005SWORD\020"
  "\000\022\007\n\003BOW\020\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_game_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_game_2eproto_sccs[3] = {
  &scc_info_Hero_game_2eproto.base,
  &scc_info_MageInfo_game_2eproto.base,
  &scc_info_WarriorInfo_game_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_game_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_game_2eproto = {
  false, false, descriptor_table_protodef_game_2eproto, "game.proto", 378,
  &descriptor_table_game_2eproto_once, descriptor_table_game_2eproto_sccs, descriptor_table_game_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_game_2eproto::offsets,
  file_level_metadata_game_2eproto, 3, file_level_enum_descriptors_game_2eproto, file_level_service_descriptors_game_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_game_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_game_2eproto)), true);
namespace game {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Spell_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_game_2eproto);
  return file_level_enum_descriptors_game_2eproto[0];
}
bool Spell_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Weapon_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_game_2eproto);
  return file_level_enum_descriptors_game_2eproto[1];
}
bool Weapon_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void WarriorInfo::InitAsDefaultInstance() {
}
class WarriorInfo::_Internal {
 public:
};

WarriorInfo::WarriorInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.WarriorInfo)
}
WarriorInfo::WarriorInfo(const WarriorInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&arrows_number_, &from.arrows_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&weapon_) -
    reinterpret_cast<char*>(&arrows_number_)) + sizeof(weapon_));
  // @@protoc_insertion_point(copy_constructor:game.WarriorInfo)
}

void WarriorInfo::SharedCtor() {
  ::memset(&arrows_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&weapon_) -
      reinterpret_cast<char*>(&arrows_number_)) + sizeof(weapon_));
}

WarriorInfo::~WarriorInfo() {
  // @@protoc_insertion_point(destructor:game.WarriorInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void WarriorInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void WarriorInfo::ArenaDtor(void* object) {
  WarriorInfo* _this = reinterpret_cast< WarriorInfo* >(object);
  (void)_this;
}
void WarriorInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void WarriorInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const WarriorInfo& WarriorInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_WarriorInfo_game_2eproto.base);
  return *internal_default_instance();
}


void WarriorInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:game.WarriorInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&arrows_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&weapon_) -
      reinterpret_cast<char*>(&arrows_number_)) + sizeof(weapon_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WarriorInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .game.Weapon weapon = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_weapon(static_cast<::game::Weapon>(val));
        } else goto handle_unusual;
        continue;
      // int64 arrows_number = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          arrows_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* WarriorInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.WarriorInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .game.Weapon weapon = 1;
  if (this->weapon() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_weapon(), target);
  }

  // int64 arrows_number = 2;
  if (this->arrows_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_arrows_number(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.WarriorInfo)
  return target;
}

size_t WarriorInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.WarriorInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 arrows_number = 2;
  if (this->arrows_number() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_arrows_number());
  }

  // .game.Weapon weapon = 1;
  if (this->weapon() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_weapon());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WarriorInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.WarriorInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const WarriorInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<WarriorInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.WarriorInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.WarriorInfo)
    MergeFrom(*source);
  }
}

void WarriorInfo::MergeFrom(const WarriorInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.WarriorInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.arrows_number() != 0) {
    _internal_set_arrows_number(from._internal_arrows_number());
  }
  if (from.weapon() != 0) {
    _internal_set_weapon(from._internal_weapon());
  }
}

void WarriorInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.WarriorInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WarriorInfo::CopyFrom(const WarriorInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.WarriorInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WarriorInfo::IsInitialized() const {
  return true;
}

void WarriorInfo::InternalSwap(WarriorInfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WarriorInfo, weapon_)
      + sizeof(WarriorInfo::weapon_)
      - PROTOBUF_FIELD_OFFSET(WarriorInfo, arrows_number_)>(
          reinterpret_cast<char*>(&arrows_number_),
          reinterpret_cast<char*>(&other->arrows_number_));
}

::PROTOBUF_NAMESPACE_ID::Metadata WarriorInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void MageInfo::InitAsDefaultInstance() {
}
class MageInfo::_Internal {
 public:
};

MageInfo::MageInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  spellbook_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.MageInfo)
}
MageInfo::MageInfo(const MageInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      spellbook_(from.spellbook_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  mana_ = from.mana_;
  // @@protoc_insertion_point(copy_constructor:game.MageInfo)
}

void MageInfo::SharedCtor() {
  mana_ = PROTOBUF_LONGLONG(0);
}

MageInfo::~MageInfo() {
  // @@protoc_insertion_point(destructor:game.MageInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MageInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void MageInfo::ArenaDtor(void* object) {
  MageInfo* _this = reinterpret_cast< MageInfo* >(object);
  (void)_this;
}
void MageInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MageInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MageInfo& MageInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MageInfo_game_2eproto.base);
  return *internal_default_instance();
}


void MageInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:game.MageInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  spellbook_.Clear();
  mana_ = PROTOBUF_LONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MageInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .game.Spell spellbook = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedEnumParser(_internal_mutable_spellbook(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_add_spellbook(static_cast<::game::Spell>(val));
        } else goto handle_unusual;
        continue;
      // int64 mana = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          mana_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MageInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.MageInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .game.Spell spellbook = 1;
  {
    int byte_size = _spellbook_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteEnumPacked(
          1, spellbook_, byte_size, target);
    }
  }

  // int64 mana = 2;
  if (this->mana() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_mana(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.MageInfo)
  return target;
}

size_t MageInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.MageInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .game.Spell spellbook = 1;
  {
    size_t data_size = 0;
    unsigned int count = static_cast<unsigned int>(this->_internal_spellbook_size());for (unsigned int i = 0; i < count; i++) {
      data_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(
        this->_internal_spellbook(static_cast<int>(i)));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _spellbook_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // int64 mana = 2;
  if (this->mana() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_mana());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MageInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.MageInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const MageInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MageInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.MageInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.MageInfo)
    MergeFrom(*source);
  }
}

void MageInfo::MergeFrom(const MageInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.MageInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  spellbook_.MergeFrom(from.spellbook_);
  if (from.mana() != 0) {
    _internal_set_mana(from._internal_mana());
  }
}

void MageInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.MageInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MageInfo::CopyFrom(const MageInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.MageInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MageInfo::IsInitialized() const {
  return true;
}

void MageInfo::InternalSwap(MageInfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  spellbook_.InternalSwap(&other->spellbook_);
  swap(mana_, other->mana_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MageInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Hero::InitAsDefaultInstance() {
  ::game::_Hero_default_instance_.warrior_info_ = const_cast< ::game::WarriorInfo*>(
      ::game::WarriorInfo::internal_default_instance());
  ::game::_Hero_default_instance_.mage_info_ = const_cast< ::game::MageInfo*>(
      ::game::MageInfo::internal_default_instance());
}
class Hero::_Internal {
 public:
  static const ::game::WarriorInfo& warrior_info(const Hero* msg);
  static const ::game::MageInfo& mage_info(const Hero* msg);
};

const ::game::WarriorInfo&
Hero::_Internal::warrior_info(const Hero* msg) {
  return *msg->class_specific_info_.warrior_info_;
}
const ::game::MageInfo&
Hero::_Internal::mage_info(const Hero* msg) {
  return *msg->class_specific_info_.mage_info_;
}
void Hero::set_allocated_warrior_info(::game::WarriorInfo* warrior_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_class_specific_info();
  if (warrior_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(warrior_info);
    if (message_arena != submessage_arena) {
      warrior_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, warrior_info, submessage_arena);
    }
    set_has_warrior_info();
    class_specific_info_.warrior_info_ = warrior_info;
  }
  // @@protoc_insertion_point(field_set_allocated:game.Hero.warrior_info)
}
void Hero::set_allocated_mage_info(::game::MageInfo* mage_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  clear_class_specific_info();
  if (mage_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(mage_info);
    if (message_arena != submessage_arena) {
      mage_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, mage_info, submessage_arena);
    }
    set_has_mage_info();
    class_specific_info_.mage_info_ = mage_info;
  }
  // @@protoc_insertion_point(field_set_allocated:game.Hero.mage_info)
}
Hero::Hero(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.Hero)
}
Hero::Hero(const Hero& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  ::memcpy(&hp_, &from.hp_,
    static_cast<size_t>(reinterpret_cast<char*>(&xp_) -
    reinterpret_cast<char*>(&hp_)) + sizeof(xp_));
  clear_has_class_specific_info();
  switch (from.class_specific_info_case()) {
    case kWarriorInfo: {
      _internal_mutable_warrior_info()->::game::WarriorInfo::MergeFrom(from._internal_warrior_info());
      break;
    }
    case kMageInfo: {
      _internal_mutable_mage_info()->::game::MageInfo::MergeFrom(from._internal_mage_info());
      break;
    }
    case CLASS_SPECIFIC_INFO_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:game.Hero)
}

void Hero::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Hero_game_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&hp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&xp_) -
      reinterpret_cast<char*>(&hp_)) + sizeof(xp_));
  clear_has_class_specific_info();
}

Hero::~Hero() {
  // @@protoc_insertion_point(destructor:game.Hero)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Hero::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (has_class_specific_info()) {
    clear_class_specific_info();
  }
}

void Hero::ArenaDtor(void* object) {
  Hero* _this = reinterpret_cast< Hero* >(object);
  (void)_this;
}
void Hero::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Hero::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Hero& Hero::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Hero_game_2eproto.base);
  return *internal_default_instance();
}


void Hero::clear_class_specific_info() {
// @@protoc_insertion_point(one_of_clear_start:game.Hero)
  switch (class_specific_info_case()) {
    case kWarriorInfo: {
      if (GetArena() == nullptr) {
        delete class_specific_info_.warrior_info_;
      }
      break;
    }
    case kMageInfo: {
      if (GetArena() == nullptr) {
        delete class_specific_info_.mage_info_;
      }
      break;
    }
    case CLASS_SPECIFIC_INFO_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = CLASS_SPECIFIC_INFO_NOT_SET;
}


void Hero::Clear() {
// @@protoc_insertion_point(message_clear_start:game.Hero)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&hp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&xp_) -
      reinterpret_cast<char*>(&hp_)) + sizeof(xp_));
  clear_class_specific_info();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Hero::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "game.Hero.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 hp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          hp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 xp = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          xp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .game.WarriorInfo warrior_info = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_warrior_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .game.MageInfo mage_info = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_mage_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Hero::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.Hero)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "game.Hero.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // int64 hp = 2;
  if (this->hp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_hp(), target);
  }

  // int64 xp = 3;
  if (this->xp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->_internal_xp(), target);
  }

  // .game.WarriorInfo warrior_info = 4;
  if (_internal_has_warrior_info()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::warrior_info(this), target, stream);
  }

  // .game.MageInfo mage_info = 5;
  if (_internal_has_mage_info()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::mage_info(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.Hero)
  return target;
}

size_t Hero::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.Hero)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // int64 hp = 2;
  if (this->hp() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_hp());
  }

  // int64 xp = 3;
  if (this->xp() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_xp());
  }

  switch (class_specific_info_case()) {
    // .game.WarriorInfo warrior_info = 4;
    case kWarriorInfo: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *class_specific_info_.warrior_info_);
      break;
    }
    // .game.MageInfo mage_info = 5;
    case kMageInfo: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *class_specific_info_.mage_info_);
      break;
    }
    case CLASS_SPECIFIC_INFO_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Hero::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.Hero)
  GOOGLE_DCHECK_NE(&from, this);
  const Hero* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Hero>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.Hero)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.Hero)
    MergeFrom(*source);
  }
}

void Hero::MergeFrom(const Hero& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.Hero)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
  if (from.hp() != 0) {
    _internal_set_hp(from._internal_hp());
  }
  if (from.xp() != 0) {
    _internal_set_xp(from._internal_xp());
  }
  switch (from.class_specific_info_case()) {
    case kWarriorInfo: {
      _internal_mutable_warrior_info()->::game::WarriorInfo::MergeFrom(from._internal_warrior_info());
      break;
    }
    case kMageInfo: {
      _internal_mutable_mage_info()->::game::MageInfo::MergeFrom(from._internal_mage_info());
      break;
    }
    case CLASS_SPECIFIC_INFO_NOT_SET: {
      break;
    }
  }
}

void Hero::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.Hero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Hero::CopyFrom(const Hero& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.Hero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Hero::IsInitialized() const {
  return true;
}

void Hero::InternalSwap(Hero* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Hero, xp_)
      + sizeof(Hero::xp_)
      - PROTOBUF_FIELD_OFFSET(Hero, hp_)>(
          reinterpret_cast<char*>(&hp_),
          reinterpret_cast<char*>(&other->hp_));
  swap(class_specific_info_, other->class_specific_info_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Hero::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::game::WarriorInfo* Arena::CreateMaybeMessage< ::game::WarriorInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::WarriorInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::game::MageInfo* Arena::CreateMaybeMessage< ::game::MageInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::MageInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::game::Hero* Arena::CreateMaybeMessage< ::game::Hero >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::Hero >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
